package com.rewardtodo.domain

import java.util.*

data class Reward(
    var title: String,
    var description: String,
    var icon: Icon,
    var imagePath: String,
    var points: Int = 1,
    var numPurchases: Int = 0,
    var userId: String = "",
    var id: String = UUID.randomUUID().toString()
) {
    enum class Icon {
        BATH,
        BEACH,
        BIKE,
        BOAT,
        BOOK,
        BOOK_CLOSED,
        CAKE,
        CAMERA,
        CAR,
        CHILD,
        CLOCK,
        COCKTAIL,
        COFFEE,
        COMPASS,
        COMPUTER,
        COUCH,
        DOODLE,
        DRINK,
        EURO,
        FIRE,
        FLIGHT,
        FLOWER,
        FRIEND,
        GAME,
        GOLF,
        HEADSET,
        LUGGAGE,
        MEAL,
        MIC,
        MONEY,
        MOTORCYCLE,
        MOUNTAINS,
        MOVIE,
        MUSIC,
        MUSIC_NOTE,
        PAINT,
        PAINTBRUSH,
        PENCIL,
        PERSON,
        PHONE,
        PHONE_CALL,
        PIZZA,
        PUZZLE,
        RUN,
        SHOPPING,
        SLEEP,
        SNACK,
        SPA,
        SPEAKER,
        STORE,
        SWIM,
        TAGS,
        TICKET,
        TRANSLATE,
        VIDEO_GAME,
        WALK,
        WORKOUT
    }
}